export enum TargetType {
  OpenCluster = 'OC',
  DarkNebula = 'DN',
  BrightNebula = 'GN',
  Galaxy = 'GX',
  Star = 'S',
  GlobularCluster = 'GC',
  Planet = 'P',
  PlanetaryNebula = 'PN',
  Comet = 'C',
  DoubleStar = 'DS',
  Asterism = 'AS',
  UnspecifiedDeepSkyObject = 'NA',
  Quasar = 'QS',
}
