export const ADD_SCOPE = 'ADD_SCOPE';
export const REMOVE_SCOPE = 'REMOVE_SCOPE';
export const SCOPES_PAGE_LOADED = 'SCOPES_PAGE_LOADED';
export const SCOPES_PAGE_UNLOADED = 'SCOPES_PAGE_UNLOADED';

export const ADD_SCOPE_PAGE_LOADED = 'ADD_SCOPE.PAGE_LOADED';
export const ADD_SCOPE_PAGE_UNLOADED = 'ADD_SCOPE.PAGE_UNLOADED';
export const ADD_SCOPE_ADD_NEW = 'ADD_SCOPE.ADD_NEW';
export const ADD_SCOPE_SCOPE_PROPERTY_CHANGED = 'ADD_SCOPE_SCOPE_PROPERTY_CHANGED';

export const EDIT_SCOPE_PAGE_LOADED = 'EDIT_SCOPE.PAGE_LOADED';
export const EDIT_SCOPE_PAGE_UNLOADED = 'EDIT_SCOPE.PAGE_UNLOADED';
export const EDIT_SCOPE_UPDATE = 'EDIT_SCOPE.UPDATE';
export const EDIT_SCOPE_SCOPE_PROPERTY_CHANGED = 'EDIT_SCOPE_SCOPE_PROPERTY_CHANGED';

